//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeUsuario02.WinForm01.Windows.Usuarios {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Retornos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Retornos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleDeUsuario02.WinForm01.Windows.Usuarios.Retornos", typeof(Retornos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar {0}º Departamento.
        /// </summary>
        internal static string AdicionarDepartamentos {
            get {
                return ResourceManager.GetString("AdicionarDepartamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário {0} atualizado com Sucesso!.
        /// </summary>
        internal static string AtualizadoComSucesso {
            get {
                return ResourceManager.GetString("AtualizadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação.
        /// </summary>
        internal static string Confirmacao {
            get {
                return ResourceManager.GetString("Confirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os campos precisão estar preenchidos!.
        /// </summary>
        internal static string CriarUsuarioErro {
            get {
                return ResourceManager.GetString("CriarUsuarioErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário: {0} {1}, de ID {2}.
        /// </summary>
        internal static string CriarUsuarioSucessoNome {
            get {
                return ResourceManager.GetString("CriarUsuarioSucessoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id: {0}, {1}.
        /// </summary>
        internal static string CriarUsuarioSucessoProjetoDepartamento {
            get {
                return ResourceManager.GetString("CriarUsuarioSucessoProjetoDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse Departamento já foi inserido nesse Usuário!.
        /// </summary>
        internal static string DepartamentoJaInserido {
            get {
                return ResourceManager.GetString("DepartamentoJaInserido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição: {0}..
        /// </summary>
        internal static string DescricaoDepartamento {
            get {
                return ResourceManager.GetString("DescricaoDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição: {0}..
        /// </summary>
        internal static string DescricaoProjeto {
            get {
                return ResourceManager.GetString("DescricaoProjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja inserir o Departamento: {0}?.
        /// </summary>
        internal static string DesejaInserirEsteDepartamento {
            get {
                return ResourceManager.GetString("DesejaInserirEsteDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o Id !.
        /// </summary>
        internal static string DigiteId {
            get {
                return ResourceManager.GetString("DigiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o Nome !.
        /// </summary>
        internal static string DigiteNome {
            get {
                return ResourceManager.GetString("DigiteNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro!.
        /// </summary>
        internal static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um erro ao tentar atualizar este Usuário..
        /// </summary>
        internal static string ErroAoAtualizar {
            get {
                return ResourceManager.GetString("ErroAoAtualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desculpe! Ocorreu um erro ao acessar a nossa Base de Dados..
        /// </summary>
        internal static string ErroDeAcessoAoBD {
            get {
                return ResourceManager.GetString("ErroDeAcessoAoBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha ao menos 1 Departamento!.
        /// </summary>
        internal static string EscolhaAoMenosUmDepartamento {
            get {
                return ResourceManager.GetString("EscolhaAoMenosUmDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha um Projeto!.
        /// </summary>
        internal static string EscolhaUmProjeto {
            get {
                return ResourceManager.GetString("EscolhaUmProjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento de Id: {0}, {1}.
        /// </summary>
        internal static string IdENomeDepartamento {
            get {
                return ResourceManager.GetString("IdENomeDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto de Id: {0}, {1}.
        /// </summary>
        internal static string IdENomeProjeto {
            get {
                return ResourceManager.GetString("IdENomeProjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id: {0}, {1} {2}.
        /// </summary>
        internal static string IdENomeUsuario {
            get {
                return ResourceManager.GetString("IdENomeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id: {0}, {1} {2}.
        /// </summary>
        internal static string MostarUsuarioCard {
            get {
                return ResourceManager.GetString("MostarUsuarioCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto {0}, de Id {1}.
        /// </summary>
        internal static string MostrarProjetoCard {
            get {
                return ResourceManager.GetString("MostrarProjetoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem {0} Departamentos.
        /// </summary>
        internal static string MostrarQuantDepartamentosCard {
            get {
                return ResourceManager.GetString("MostrarQuantDepartamentosCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum Departamento foi inserido!.
        /// </summary>
        internal static string NenhumDepartamentoInserido {
            get {
                return ResourceManager.GetString("NenhumDepartamentoInserido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum usuário foi encontrado!
        ///{0}.
        /// </summary>
        internal static string NenhumUsuarioEncontrado {
            get {
                return ResourceManager.GetString("NenhumUsuarioEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha todos os campos do Novo Projeto.
        ///Ou selecione um já existente..
        /// </summary>
        internal static string PreenchaOsCamposNovoProjeto {
            get {
                return ResourceManager.GetString("PreenchaOsCamposNovoProjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha todos os campos!.
        /// </summary>
        internal static string PreenchaTodosCampos {
            get {
                return ResourceManager.GetString("PreenchaTodosCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Projeto {1} {2}.
        /// </summary>
        internal static string ProjetoCompleto {
            get {
                return ResourceManager.GetString("ProjetoCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha se será um novo Projeto ou um existente..
        /// </summary>
        internal static string SelecionePorjetoNovoOuExistente {
            get {
                return ResourceManager.GetString("SelecionePorjetoNovoOuExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso!.
        /// </summary>
        internal static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentar novamente?.
        /// </summary>
        internal static string TentarNovamente {
            get {
                return ResourceManager.GetString("TentarNovamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário de Id {0} não foi encontrado!.
        /// </summary>
        internal static string UsuairoNaoEncontrado {
            get {
                return ResourceManager.GetString("UsuairoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário {0} criado com Sucesso!
        ///
        ///Recebeu um Id {1}..
        /// </summary>
        internal static string UsuarioCriadoComSucesso {
            get {
                return ResourceManager.GetString("UsuarioCriadoComSucesso", resourceCulture);
            }
        }
    }
}
