//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeUsuario02.WinForm01 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleDeUsuario02.WinForm01.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado!.
        /// </summary>
        internal static string BuscarPorIdErro {
            get {
                return ResourceManager.GetString("BuscarPorIdErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite um Id..
        /// </summary>
        internal static string BuscarPorIdNãoDigitado {
            get {
                return ResourceManager.GetString("BuscarPorIdNãoDigitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id {0} do Departamento {1}.
        /// </summary>
        internal static string BuscarPorIdSucessoDepartmento {
            get {
                return ResourceManager.GetString("BuscarPorIdSucessoDepartmento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} de Id {2} Faz parte do Projeto {3}.
        /// </summary>
        internal static string BuscarPorIdSucessoUsuarioProjeto {
            get {
                return ResourceManager.GetString("BuscarPorIdSucessoUsuarioProjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação Cancelado!.
        /// </summary>
        internal static string Cancelado {
            get {
                return ResourceManager.GetString("Cancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia:  {0}.
        /// </summary>
        internal static string DiaEMes {
            get {
                return ResourceManager.GetString("DiaEMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro!.
        /// </summary>
        internal static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não conseguimos acessar a base de dados..
        /// </summary>
        internal static string ErroAoAcessarBD {
            get {
                return ResourceManager.GetString("ErroAoAcessarBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:/Program Files/Google/Chrome/Application/chrome.exe.
        /// </summary>
        internal static string GoogleChrome {
            get {
                return ResourceManager.GetString("GoogleChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file://C:\\project\\ProjetoStartFilipe\\ControleDeUsuario02\\ControleDeUsuario02.WinForm01\\Resources\\Help.html.
        /// </summary>
        internal static string HelpPage {
            get {
                return ResourceManager.GetString("HelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitura cancelada!.
        /// </summary>
        internal static string LeituraCancelado {
            get {
                return ResourceManager.GetString("LeituraCancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leitura finalizado com sucesso!.
        /// </summary>
        internal static string LeituraDocumentoFinalizado {
            get {
                return ResourceManager.GetString("LeituraDocumentoFinalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem acesso ao banco.
        /// </summary>
        internal static string SemAcessoBanco {
            get {
                return ResourceManager.GetString("SemAcessoBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso!.
        /// </summary>
        internal static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
    }
}
