//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeUsuario02.WinForm01.Windows.Projetos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Retornos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Retornos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleDeUsuario02.WinForm01.Windows.Projetos.Retornos", typeof(Retornos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção.
        /// </summary>
        internal static string Atencao {
            get {
                return ResourceManager.GetString("Atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar projeto de Id {0}.
        /// </summary>
        internal static string AtualizarProjeto {
            get {
                return ResourceManager.GetString("AtualizarProjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição: {0}..
        /// </summary>
        internal static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o Id !.
        /// </summary>
        internal static string DigiteId {
            get {
                return ResourceManager.GetString("DigiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro!.
        /// </summary>
        internal static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Desculpe! Ocorreu um erro ao
        ///  acessar a nossa Base de Dados..
        /// </summary>
        internal static string ErroDeAcessoAoDB {
            get {
                return ResourceManager.GetString("ErroDeAcessoAoDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto de Id: {0}, {1}.
        /// </summary>
        internal static string IdENomeProjeto {
            get {
                return ResourceManager.GetString("IdENomeProjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    É necessário alguma mudança
        ///   em um dos campos..
        /// </summary>
        internal static string NecessarioMudanca {
            get {
                return ResourceManager.GetString("NecessarioMudanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum Projeto foi encontrado!.
        /// </summary>
        internal static string NenhumProjetoEncontrado {
            get {
                return ResourceManager.GetString("NenhumProjetoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível inserir um novo Projeto!.
        /// </summary>
        internal static string NovoProjetoErro {
            get {
                return ResourceManager.GetString("NovoProjetoErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto {0} inserido com id {1}..
        /// </summary>
        internal static string NovoProjetoSucesso {
            get {
                return ResourceManager.GetString("NovoProjetoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha todos os campos!.
        /// </summary>
        internal static string PreenchaTodosCampos {
            get {
                return ResourceManager.GetString("PreenchaTodosCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Projeto de Id {0} não foi encontrado..
        /// </summary>
        internal static string ProjetoNaoEncontrado {
            get {
                return ResourceManager.GetString("ProjetoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso!.
        /// </summary>
        internal static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
    }
}
